# Generated by Django 4.1.3 on 2022-12-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('fechaInscripcion', models.DateField()),
                ('institucion', models.IntegerField()),
                ('horaInscripcion', models.TimeField()),
                ('estado', models.IntegerField(choices=[[0, 'Reservado'], [1, 'Completada'], [2, 'Anulada'], [3, 'No asisten']])),
                ('observacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.IntegerField()),
            ],
        ),
    ]
