# Generated by Django 4.1.3 on 2022-12-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminarioApp', '0003_alter_institucion_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='institucion',
            field=models.IntegerField(),
        ),
    ]
