# Generated by Django 4.1.3 on 2022-12-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminarioApp', '0004_alter_institucion_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='institucion',
            field=models.CharField(max_length=50),
        ),
    ]
